#STEP 1 ================================================
#base image
FROM node:9.6.1 as builder

#set working directory
RUN mkdir /usr/src/app
WORKDIR /usr/src/app

# add `/usr/src/app/node_modules/.bin` to $PATH
#ENV PATH /usr/src/app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json /usr/src/app/package.json
RUN npm install

#COPY . ./
COPY . /usr/src/app
#RUN npm install react-scripts@1.1.1 -g

# start app
#CMD ["npm", "run", "build"]
RUN npm run build
#==========================================================

# Stage 2 - the production environment ====================
FROM nginx:alpine
#COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /usr/src/app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
#==========================================================