version: '2'

services:
  tic-tac-toe:
    container_name: tic-tac-toe
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development